# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cbe30ff6770d9974d739ab3c9df909a222c39bb9fa93c3063b725074ca92fc753643eb24cd83a818fa066f84d75fc7ebd131ff7a96f94615d17480ee75b900d

test:
  secret_key_base: 2854fe17009a44b5d672016f85363abcad6c8eb9721afc64cea0f0b77eb44fdcdbe7681302ba635cd2ccb9d0a52e6aae5ff3ca818415729ec8f811d3793eef0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
